### ISSUE TITLE
Download links to classifiers are broken

### ISSUE THREAD

**Issue by daphnei** [dykang/xslue#4]
Are these models still available for download somewhere?

Thanks!

**Comment by dykang** [comment]
Hi, Daphne

Sorry for the late reply. I had to recover previous model files and other scripts, making me additional days of delays. You can now check the downloading scripts here: https://github.com/dykang/xslue/blob/master/README.md#download-xslue-data-and-fine-tuned-classifiers
Also, the links to the pre-trained models are alive now. 

Thank you!

**Comment by dykang** [comment]
Hi, Daphne

Sorry for the late reply. I had to recover previous model files and other
scripts, making me additional days of delays. You can now check the
downloading scripts here:
https://github.com/dykang/xslue/blob/master/README.md#download-xslue-data-and-fine-tuned-classifiers
Also, the links to the pre-trained models are alive now.

Thank you!
