### ISSUE TITLE
Pytorch_model.bin missing

### ISSUE THREAD

**Issue by jacksukk** [dykang/xslue#6]
Hi! Thanks for this awesome work!

I'm wondering if it's possible to release the pre-trained pytorch_model.bin file on google drive?
I checked it and didn't found the pre-trained model in the folders.

Thank you very much.

**Comment by dykang** [comment]
The link provided in README.md is currently not working. Please use this google drive link to download the model parameters: https://drive.google.com/drive/folders/1JcpY638OBM6zQFuRXZU0IzqtXaueAHcZ?usp=sharing

**Comment by jacksukk** [comment]
Thanks for the kind response.
I checked the google link, but I found that the checkpoint of the bert-based model was still missed.
https://drive.google.com/drive/folders/1i_MvWicbxUPheJ_sAxZXQDRu8oen-D1z
Could you help me, thank you.

**Comment by dykang** [comment]
Hi, I just found that there was an issue while uploading the model files.
I'm uploading them right now. Could you please check them out after 24
hours later?
--
Regards,
Dongyeop
