### ISSUE TITLE
Unable to download

### ISSUE THREAD

**Issue by qhd1996** [dykang/xslue#8]
Downloading 
--2022-04-01 18:17:27--  http://dongtae.lti.cs.cmu.edu/data/xslue_model_v0.1/PASTEL.zip
Resolving dongtae.lti.cs.cmu.edu (dongtae.lti.cs.cmu.edu)... failed: Name or service not known.
wget: unable to resolve host address 'dongtae.lti.cs.cmu.edu'

**Comment by dykang** [comment]
Sorry for the inconvenience. Since I graduated, the host server is no longer available. Instead, you can download them here: https://drive.google.com/drive/folders/1N78VdtGGXw_aOpnOd6SOOCXcgGe1zCsO?usp=sharing
